# Generated by Django 4.2.28 on 2026-02-26 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Advisory Category',
                'verbose_name_plural': 'Advisory Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('presenter_title', models.CharField(blank=True, max_length=100)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('youtube', 'YouTube Live'), ('facebook', 'Facebook Live'), ('teams', 'Microsoft Teams')], max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting_password', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live Now'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to=settings.AUTH_USER_MODEL)),
                ('registered_users', models.ManyToManyField(blank=True, related_name='registered_webinars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinars',
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeleVetConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_species', models.CharField(max_length=50)),
                ('animal_breed', models.CharField(blank=True, max_length=100)),
                ('animal_age', models.CharField(blank=True, max_length=50)),
                ('symptoms', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='vet_consultations/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='vet_consultations/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='vet_consultations/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tele-Vet Consultation',
                'verbose_name_plural': 'Tele-Vet Consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('display_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisory.advisorycategory')),
                ('related_crops', models.ManyToManyField(blank=True, to='crops.crop')),
            ],
            options={
                'verbose_name': 'Farming Tip',
                'verbose_name_plural': 'Farming Tips',
                'ordering': ['-display_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisory.advisorycategory')),
                ('related_crops', models.ManyToManyField(blank=True, to='crops.crop')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-view_count'],
            },
        ),
        migrations.CreateModel(
            name='ExpertConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('contact_method', models.CharField(choices=[('phone', 'Phone Call'), ('video', 'Video Call'), ('chat', 'Chat')], max_length=20)),
                ('contact_details', models.CharField(max_length=100)),
                ('expert_notes', models.TextField(blank=True)),
                ('farmer_feedback', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisory.advisorycategory')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_consultations', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expert Consultation',
                'verbose_name_plural': 'Expert Consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='advisory/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('ki', 'Kikuyu'), ('lu', 'Luo'), ('ka', 'Kalenjin'), ('kl', 'Kamba')], default='en', max_length=2)),
                ('author_title', models.CharField(blank=True, max_length=100, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='advisory.advisorycategory')),
                ('related_crops', models.ManyToManyField(blank=True, related_name='advisory_articles', to='crops.crop')),
            ],
            options={
                'verbose_name': 'Advisory Article',
                'verbose_name_plural': 'Advisory Articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
