# Generated by Django 4.2.28 on 2026-02-24 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Farm Name')),
                ('farm_size', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Farm Size')),
                ('farm_size_unit', models.CharField(choices=[('acres', 'Acres'), ('hectares', 'Hectares'), ('sq_km', 'Square Kilometers')], default='acres', max_length=10, verbose_name='Farm Size Unit')),
                ('farm_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Farm Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('soil_type', models.CharField(choices=[('clay', 'Clay Soil'), ('sandy', 'Sandy Soil'), ('loam', 'Loam Soil'), ('silt', 'Silt Soil'), ('peat', 'Peat Soil'), ('chalky', 'Chalky Soil'), ('black_cotton', 'Black Cotton Soil'), ('red', 'Red Soil'), ('alluvial', 'Alluvial Soil'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Soil Type')),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Soil pH')),
                ('soil_fertility', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Soil Fertility')),
                ('farming_type', models.CharField(choices=[('subsistence', 'Subsistence Farming'), ('commercial', 'Commercial Farming'), ('mixed', 'Mixed Farming'), ('organic', 'Organic Farming')], default='subsistence', max_length=20, verbose_name='Farming Type')),
                ('irrigation_method', models.CharField(choices=[('rainfed', 'Rain-fed'), ('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler Irrigation'), ('furrow', 'Furrow Irrigation'), ('flood', 'Flood Irrigation'), ('center_pivot', 'Center Pivot'), ('manual', 'Manual Watering')], default='rainfed', max_length=20, verbose_name='Irrigation Method')),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Income (KES)')),
                ('has_loan', models.BooleanField(default=False, verbose_name='Has Active Loan')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Loan Amount (KES)')),
                ('credit_score', models.IntegerField(default=0, verbose_name='Credit Score')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Limit (KES)')),
                ('is_subsidy_beneficiary', models.BooleanField(default=False, verbose_name='Subsidy Beneficiary')),
                ('subsidy_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subsidy Type')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('is_cooperative_member', models.BooleanField(default=False, verbose_name='Cooperative Member')),
                ('cooperative_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cooperative Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_name', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_unit', models.CharField(choices=[('acres', 'Acres'), ('hectares', 'Hectares'), ('sq_km', 'Square Kilometers')], default='acres', max_length=10)),
                ('boundary_coordinates', models.JSONField(blank=True, help_text='GPS coordinates of parcel boundary', null=True)),
                ('current_crop', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('soil_type', models.CharField(choices=[('clay', 'Clay Soil'), ('sandy', 'Sandy Soil'), ('loam', 'Loam Soil'), ('silt', 'Silt Soil'), ('peat', 'Peat Soil'), ('chalky', 'Chalky Soil'), ('black_cotton', 'Black Cotton Soil'), ('red', 'Red Soil'), ('alluvial', 'Alluvial Soil'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='farmers.farmerprofile')),
            ],
            options={
                'verbose_name': 'Farm Parcel',
                'verbose_name_plural': 'Farm Parcels',
                'ordering': ['parcel_name'],
            },
        ),
        migrations.CreateModel(
            name='FarmingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_variety', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(choices=[('short_rains', 'Short Rains (Oct-Dec)'), ('long_rains', 'Long Rains (Mar-May)'), ('dry_season', 'Dry Season (Jun-Sep)')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('area_planted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yield_unit', models.CharField(choices=[('kg', 'Kilograms'), ('tonnes', 'Tonnes'), ('bags_90kg', 'Bags (90kg)'), ('bags_50kg', 'Bags (50kg)')], default='kg', max_length=20)),
                ('seed_variety', models.CharField(blank=True, max_length=100, null=True)),
                ('fertilizer_used', models.TextField(blank=True)),
                ('pesticides_used', models.TextField(blank=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_history', to='farmers.farmerprofile')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_history', to='farmers.farmparcel')),
            ],
            options={
                'verbose_name': 'Farming History',
                'verbose_name_plural': 'Farming History',
                'ordering': ['-year', '-season'],
            },
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('input', 'Input Financing'), ('equipment', 'Equipment Loan'), ('seasonal', 'Seasonal Loan'), ('insurance', 'Insurance Premium'), ('emergency', 'Emergency Loan')], max_length=50)),
                ('lender_name', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('application_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_score_impact', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_history', to='farmers.farmerprofile')),
            ],
            options={
                'verbose_name': 'Credit History',
                'verbose_name_plural': 'Credit History',
                'ordering': ['-application_date'],
            },
        ),
    ]
