# Generated by Django 4.2.28 on 2026-02-26 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('drought', 'Drought Warning'), ('flood', 'Flood Warning'), ('heavy_rain', 'Heavy Rain Warning'), ('frost', 'Frost Warning'), ('heatwave', 'Heatwave Warning'), ('strong_wind', 'Strong Wind Warning'), ('pest_outbreak', 'Pest Outbreak Alert'), ('disease_outbreak', 'Disease Outbreak Alert'), ('planting', 'Planting Advisory'), ('harvest', 'Harvest Advisory')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe'), ('extreme', 'Extreme')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('counties', models.JSONField(default=list)),
                ('specific_areas', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('effective_from', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('recommended_actions', models.TextField()),
                ('crops_affected', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='KMD', max_length=100)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Climate Alert',
                'verbose_name_plural': 'Climate Alerts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('forecast_date', models.DateField()),
                ('forecast_time', models.TimeField()),
                ('temperature_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.PositiveIntegerField(blank=True, null=True)),
                ('weather_condition', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=100)),
                ('weather_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('precipitation_probability', models.PositiveIntegerField(default=0)),
                ('precipitation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather Forecast',
                'verbose_name_plural': 'Weather Forecasts',
                'ordering': ['forecast_date', 'forecast_time'],
                'unique_together': {('county', 'sub_county', 'forecast_date', 'forecast_time')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feels_like', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.PositiveIntegerField()),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('weather_condition', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=100)),
                ('weather_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_direction', models.PositiveIntegerField(blank=True, null=True)),
                ('visibility', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cloud_coverage', models.PositiveIntegerField(blank=True, null=True)),
                ('rain_1h', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rain_3h', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-timestamp'],
                'unique_together': {('county', 'sub_county', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='IrrigationAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loam', 'Loam'), ('silt', 'Silt')], max_length=20)),
                ('growth_stage', models.CharField(choices=[('germination', 'Germination'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('maturity', 'Maturity')], max_length=20)),
                ('temperature_range_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature_range_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('irrigation_frequency', models.CharField(max_length=100)),
                ('water_amount_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('best_time', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_advice', to='crops.crop')),
            ],
            options={
                'verbose_name': 'Irrigation Advice',
                'verbose_name_plural': 'Irrigation Advice',
            },
        ),
        migrations.CreateModel(
            name='UserWeatherSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_types', models.JSONField(default=list)),
                ('min_severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe'), ('extreme', 'Extreme')], default='moderate', max_length=10)),
                ('sms_alerts', models.BooleanField(default=True)),
                ('email_alerts', models.BooleanField(default=False)),
                ('push_alerts', models.BooleanField(default=True)),
                ('crops', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weather Subscription',
                'verbose_name_plural': 'Weather Subscriptions',
                'unique_together': {('user', 'county', 'sub_county')},
            },
        ),
    ]
